name: Check Adapters

permissions:
  contents: write

on:
  push:
    branches:
      - main
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  # Allows manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Update submodules
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git submodule update --init --recursive
          cd euler-interfaces
          git fetch --all
          git remote set-branches origin '*'
          git fetch origin new-deployments
          git checkout new-deployments
          git pull origin new-deployments
          cd ..
          git add euler-interfaces
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update euler-interfaces submodule" && git push)

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Generate .env file
        run: |
          echo '${{ secrets.RPC_URLS }}' > rpc_urls.json
          for KEY in $(jq -r 'keys[]' rpc_urls.json); do
            VALUE=$(jq -r ".[\"$KEY\"]" rpc_urls.json)
            echo "RPC_URL_$KEY=$VALUE" >> .env
          done
          rm rpc_urls.json

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run start

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git pull  # Ensure we have latest changes
          git add -f data/  # Force add data directory even if gitignored
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update adapter check results" && git push)
